# Generated by Django 4.2.9 on 2024-02-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRelation',
            fields=[
                ('owner_name', models.CharField(max_length=100)),
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RenterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=50)),
                ('date_of_arrival', models.DateField()),
                ('owner_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='relation.ownerrelation')),
            ],
        ),
    ]
