# Generated by Django 4.2.9 on 2024-02-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_auth', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
