# Generated by Django 4.2.9 on 2024-02-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_auth', '0005_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
